[package]
name = "tiny_os"
version = "0.1.0"
edition = "2021"
authors = ["sheep<ysj1173886760@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-macro = "2.1.1"